#!/usr/bin/env bash

Ish=$(cd $( dirname "${BASH_SOURCE[0]}" ) && pwd )/..
chmod +x $Ish/etc/ish
mkdir -p $Ish/docs

alias ls="ls -G"
alias gp="git add *; git commit -am saving; git push; git status"
alias ish="$Ish/etc/ish "
alias reload=" . $Ish/etc/ish"
alias vi='vim -u /Users/timm/.vimrc'

here() { cd $1; basename `pwd`; }

PROMPT_COMMAND='echo -ne  "🎯 $(git branch 2>/dev/null | grep '^*' | colrm 1 2):";PS1="$(here ..)/$(here .):\!\e[m ▶ "'

doc1() { gawk '
    BEGIN              { First=1 }
    NR==1              { print "\n# " FILENAME "\n" }
    /vim:/             { next    }
    END                { if(!In) print "````\n"        }
     { if (gsub(/^# /,"")) {
         if (!In) {if(!First) print "```\n\n"$0; First=0; In=1;next}}
       else
         if (In)  {print "\n```julia\n" $0; In=0;next}
    }
    {  print }' $1 
}
patch() { gawk '
/^```$/ && !last { last="```"; next    }
                 { print last; last=$0 }
END              { print last          }'
}

if [ "$1" == "-d" ]; then
  cp $Ish/README.md $Ish/docs/index.md
  (cd $Ish/src
  for f in *.jl; do 
    g=$Ish/docs/${f%.*}.md
    if [ "$f" -nt "$g" ]; then
      doc1 $f | patch > $Ish/docs/${f%.*}.md
    fi
  done)
fi
